export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESSS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
export const RESET_STATE = "RESET_STATE";
